server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8282
  address: 0.0.0.0

logging:
  level:
    #root: debug
    org.springframework.security: DEBUG
    jdbc.sqlonly: debug
    log4jdbc.log4j2: warn
    jdbc.sqltiming: off
    jdbc.resultsettable: off
    jdbc.audit: off
    jdbc.connection: off

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:oracle:thin:@localhost:1521/XE
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      pool-name: HikariPool
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  devtools:
    restart:
      exclude:
      additional-paths: src/main/java
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8282/login/oauth2/code/naver
          kakao:
            client-id:
            client-secret:
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8282/login/oauth2/code/kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 respones에 담아서 넘겨줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret-key: ${JWT_SECRET-KEY}