server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8282
  address: 0.0.0.0

logging:
  level:
    #root: debug
    org.springframework.security: DEBUG
    jdbc.sqlonly: debug
    log4jdbc.log4j2: warn
    jdbc.sqltiming: off
    jdbc.resultsettable: off
    jdbc.audit: off
    jdbc.connection: off

spring:
  profiles:
    active: env, db, oauth, mail
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      exclude:
      additional-paths: src/main/java
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html